AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1